package edu.depaul.se.servlet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;
import javax.sql.DataSource;

/**
 * Application Lifecycle Listener implementation class ServletInialization
 *
 */
@WebListener
public class ServletInialization implements ServletContextListener {

    /**
     * Default constructor.
     */
    public ServletInialization() {
    }

    static {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
        } catch (ClassNotFoundException cnfe) {
            cnfe.printStackTrace();
        }
    }

    /**
     * @see ServletContextListener#contextInitialized(ServletContextEvent)
     */
    public void contextInitialized(ServletContextEvent arg0) {
        System.out.println("--> SI Creating Accounts table");

        try {
            Context initContext = new InitialContext();
            Context envContext = (Context) initContext.lookup("java:/comp/env");
            DataSource ds = (DataSource) envContext.lookup("jdbc/TestDB");

            System.out.println("Before regular table creation");
            createAccount(DriverManager.getConnection("jdbc:hsqldb:mem:SE452", "", ""));
            System.out.println("After regular table creation");

            System.out.println("Before jdbcDriver");
            createAccount(ds.getConnection());
            System.out.println("After datasource table creation");
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        System.out.println("--> SI Created Account table");
    }

    private void createAccount(Connection con) throws SQLException {
        try (Statement stmt = con.createStatement()) {
            stmt.executeUpdate("create table ACCOUNTS (ID integer GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, NM VARCHAR(50), Balance float)");
            stmt.executeUpdate("insert into accounts(id, nm, balance) values (200, 'Baker', 11.11)");
            stmt.executeUpdate("insert into accounts(id, nm, balance) values (201, 'Charley', 22.22)");
            stmt.executeUpdate("insert into accounts(id, nm, balance) values (202, 'Delta', 33.33)");
        }
    }

    /**
     * @see ServletContextListener#contextDestroyed(ServletContextEvent)
     */
    public void contextDestroyed(ServletContextEvent arg0) {
    }

}
