package edu.depaul.se.account.persistence;

import edu.depaul.se.account.business.AccountManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import org.junit.After;
import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.test.annotation.Rollback;

/**
 * Test account persistence
 */
public class AccountTest {

    private static EntityManagerFactory entityManagerFactory;

    private EntityManager entityManager;

    /**
     * Setup data for the test
     * @throws java.sql.SQLException
     */
    @BeforeClass
    public static void beforeClass() throws SQLException {
        entityManagerFactory = Persistence.createEntityManagerFactory("jpa-inMemoryDemoPU");
        String connectionUrl = "jdbc:hsqldb:mem:SE452";
        String userName = "";
        String password = "";

        try (Connection con = DriverManager.getConnection(connectionUrl, userName, password)) {
            // Step 3:  Create a statement where the SQL statement will be provided
            Statement stmt = con.createStatement();
            
            stmt.executeUpdate("drop table ACCOUNTS");
            
            stmt.executeUpdate("create table ACCOUNTS (ID integer GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, NM VARCHAR(50), Balance float)");
            stmt.executeUpdate("insert into accounts(id, nm, balance) values (200, 'Baker', 11.11)");
            stmt.executeUpdate("insert into accounts(id, nm, balance) values (201, 'Charley', 22.22)");
            stmt.executeUpdate("insert into accounts(id, nm, balance) values (202, 'Delta', 33.33)");
        }
    }

    @Before
    public void beforeEachTest() {
        entityManager = entityManagerFactory.createEntityManager();
    }

    @After
    public void afterEachTest() {
        entityManager.close();
    }
    @Test
    @Rollback
    public void testInsert() {
        entityManager.getTransaction().begin();
        Account account = new Account();
        account.setBalance(100);
        long newAccount = (long) new Random().nextInt();
        account.setId(newAccount);
        account.setName("Abe");

        // Persist the customer
        entityManager.persist(account);

        entityManager.getTransaction().commit();

        Account verification = findAccount(newAccount);
        assertEquals("Customer name", verification.getName(), account.getName());
        assertEquals("Balance", verification.getBalance(), account.getBalance(), 0.0);
    }
    
    @Test
    public void countAccount() {
        Query q = entityManager.createQuery("select c from Account c");
        assertEquals(3, q.getResultList().size());
    }
    
    private Account findAccount(long accountId) {
        Query q = entityManager.createQuery("select c from Account c where c.id = :id");
        q.setParameter("id", accountId);
        return (Account) q.getSingleResult();
    }

}
