package edu.depaul.se.servlet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import static org.junit.Assert.assertTrue;
import org.junit.Before;
import org.junit.BeforeClass;

import org.junit.Test;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

public class UserServletTest {

    private static boolean initialized = false;

    @BeforeClass
    public static void setupTable() {
        if (initialized == false) {

            String connectionUrl = "jdbc:hsqldb:mem:.";
            String userName = "";
            String password = "";

            Connection con;
            try {
                con = DriverManager.getConnection(connectionUrl, userName, password);
                // Step 3:  Create a statement where the SQL statement will be provided
                Statement stmt = con.createStatement();
                stmt.executeUpdate("create table USERS(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, name varchar(50))");
                stmt.executeUpdate("INSERT INTO users (name) values('Kid')");
                stmt.executeUpdate("INSERT INTO users (name) values('Rob')");
                stmt.executeUpdate("INSERT INTO users (name) values('Dave')");
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            initialized = true;
        }

    }
    private MockHttpServletRequest request = new MockHttpServletRequest();
    private MockHttpServletResponse response = new MockHttpServletResponse();
    private UserServlet servlet = new UserServlet();

    @Before
    public void setUp() {
        servlet = new UserServlet();
        request = new MockHttpServletRequest();
        response = new MockHttpServletResponse();
    }

    @Test
    public void testHandleRequest() throws Exception {
        servlet.doGet(request, response);

        // Rudamentary test to see if the user is in the list
        assertTrue(response.getContentAsString().contains("users.User"));
    }
}
