package edu.depaul.se.account;

import edu.depaul.se.account.persistence.Account;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class Main {

    public static void main(String[] args) throws Exception {
        String connectionUrl = "jdbc:hsqldb:mem:.";
        String userName = "";
        String password = "";

        Connection con = DriverManager.getConnection(connectionUrl, userName, password);
        
        Statement stmt = con.createStatement();
        stmt.executeUpdate("create table ACCOUNTS (ID integer GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, NM VARCHAR(50), Balance float)");
        stmt.executeUpdate("insert into accounts(id, nm, balance) values (200, 'Baker', 11.11)");
        stmt.executeUpdate("insert into accounts(id, nm, balance) values (201, 'Charley', 22.22)");
        stmt.executeUpdate("insert into accounts(id, nm, balance) values (202, 'Delta', 33.33)");

        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("accountPU");
        EntityManager entityManager = entityManagerFactory.createEntityManager();
        entityManager.getTransaction().begin();
        Account account = new Account();
        account.setBalance(100);
        long newAccount = (long) 1;
        account.setId(newAccount);
        account.setName("Abe");

        // Persist the customer
        entityManager.persist(account);

        entityManager.getTransaction().commit();

        entityManager.close();

     }
}
