--Drop any existing tables
DROP TABLE Account_Transfer_Debit IF EXISTS;
DROP TABLE Debit_Card_Transactions IF EXISTS;
DROP TABLE Check_Debit IF EXISTS;
DROP TABLE Bill_Pay_Debit IF EXISTS;
DROP TABLE Debits IF EXISTS;
DROP TABLE Credits IF EXISTS;
DROP TABLE Other_Bank_Account IF EXISTS;
DROP TABLE Holder_To_Account_Map IF EXISTS;	
DROP TABLE Account_Holder_Login IF EXISTS;
DROP TABLE Account_Holder IF EXISTS;
DROP TABLE Account IF EXISTS;


--Begin table creation
CREATE TABLE Account_Holder
	(User_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
	 First_Name VARCHAR(25) NOT NULL,
	 Middle_Name VARCHAR(25),
	 Last_Name VARCHAR(25) NOT NULL,
	 Title VARCHAR(4),
	 SSN VARCHAR(11) UNIQUE NOT NULL,
	 Mailing_Address VARCHAR(100) NOT NULL,
	 Mailing_City VARCHAR(100) NOT NULL,
	 Mailing_State VARCHAR(2) NOT NULL,
	 Mailing_Zip VARCHAR(10) NOT NULL,
	 Physical_Address VARCHAR(100) NOT NULL,
	 Physical_City VARCHAR(100) NOT NULL,
	 Physical_State VARCHAR(2) NOT NULL,
	 Physical_Zip VARCHAR(10) NOT NULL,
	 Phone VARCHAR(12),
	 Email_Address VARCHAR(100),
	 Employer_Name VARCHAR(100),
	 Employer_Phone VARCHAR(12),
	 Salary INTEGER,
	 PRIMARY KEY (User_ID));
 
CREATE TABLE Other_Bank_Account
	(Bank_Routing_Number VARCHAR(9) NOT NULL,
	 Account_Number VARCHAR(15) NOT NULL,
	 User_ID_FK INTEGER NOT NULL,
	 Bank_Name VARCHAR(50),
	 Bank_Address VARCHAR(100),
	 PRIMARY KEY (Bank_Routing_Number, Account_Number, User_ID_FK),
	 FOREIGN KEY (User_ID_FK) REFERENCES Account_Holder(User_ID));
	 
CREATE TABLE Account_Holder_Login
	(USER_ID INTEGER NOT NULL,
	 User_Name VARCHAR(50) NOT NULL,
	 Password VARCHAR(50) NOT NULL,
	 Enabled INTEGER NOT NULL,
	 Authority VARCHAR(50)
	 PRIMARY KEY (User_ID),
	 FOREIGN KEY (User_ID) REFERENCES Account_Holder(User_ID));

CREATE TABLE Account 
	(Account_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
	 Account_Type VARBINARY(255) NOT NULL,
	 Balance DOUBLE NOT NULL, 
	 Interest_Rate Double,
	 PRIMARY KEY (Account_ID));

CREATE TABLE Holder_To_Account_Map
	(User_ID_FK INTEGER NOT NULL,
	 Account_ID_FK INTEGER NOT NULL,
	 Ownership_Type VARBINARY(255),
	 PRIMARY KEY (User_ID_FK, Account_ID_FK),
	 FOREIGN KEY (User_ID_FK, Account_ID_FK) REFERENCES Account_Holder(User_ID),
	 FOREIGN KEY (Account_ID_FK) REFERENCES Account(Account_ID));
	 
CREATE TABLE Credits
	(Credit_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
	 Credit_Type VARCHAR(50) NOT NULL,
	 Account_ID_FK INTEGER NOT NULL,
	 Amount DOUBLE NOT NULL,
	 Posted_Date DATE NOT NULL,
	 Category VARCHAR(100),
	 Balance DOUBLE NOT NULL,
	 Description VARCHAR(100),
	 PRIMARY KEY (Credit_ID),
	 FOREIGN KEY (Account_ID_FK) REFERENCES Account(Account_ID));
	 
CREATE TABLE Debits
	(Debit_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
	 Account_ID_FK INTEGER NOT NULL,
	 Amount DOUBLE NOT NULL,
	 Posted_Date DATE NOT NULL,
	 Debit_Type VARCHAR(50),
	 Balance DOUBLE NOT NULL,
	 PRIMARY KEY (Debit_ID),
	 FOREIGN KEY (Account_ID_FK) REFERENCES Account(Account_ID));
	 
CREATE TABLE Bill_Pay_Debit
	(Debit_ID_FK INTEGER NOT NULL,
	 Company_Name VARCHAR(50) NOT NULL,
	 Additional_Details VARCHAR(100),
	 Transaction_Description VARCHAR(100),
	 Customer_Name VARCHAR(50) NOT NULL,
	 PRIMARY KEY (Debit_ID_FK),
	 FOREIGN KEY (Debit_ID_FK) REFERENCES Debits(Debit_ID));
	 
CREATE TABLE Check_Debit
	(Debit_ID_FK INTEGER NOT NULL,
	 Check_Number INTEGER,
	 PRIMARY KEY (Debit_ID_FK),
	 FOREIGN KEY (Debit_ID_FK) REFERENCES Debits(Debit_ID));

CREATE TABLE Debit_Card_Transactions
	(Debit_ID_FK INTEGER NOT NULL,
	 Merchant_Info VARCHAR(100) NOT NULL,
	 Merchant_Type VARCHAR(25),
	 Transaction_Type VARCHAR(25),
	 Debit_Card_Number VARCHAR(25) NOT NULL,
	 Authorization_Date DATE NOT NULL,
	 Card_Holder_ID INTEGER NOT NULL,
	 PRIMARY KEY (Debit_ID_FK),
	 FOREIGN KEY (Debit_ID_FK) REFERENCES Debits(Debit_ID),
	 FOREIGN KEY (Card_Holder_ID) REFERENCES Account_Holder(User_ID));	 
	 
CREATE TABLE Account_Transfer_Debit
	(Debit_ID_FK INTEGER NOT NULL,
	 Credited_Account_ID INTEGER,
	 PRIMARY KEY (Debit_ID_FK),
	 FOREIGN KEY (Debit_ID_FK) REFERENCES Debits(Debit_ID),
	 FOREIGN KEY (Credited_Account_ID) REFERENCES Account(Account_ID));