package edu.depaul.cdm.se.servlet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;
import javax.sql.DataSource;

/**
 * Application Lifecycle Listener implementation class ServletInialization
 *
 */
@WebListener
public class InitializationServlet implements ServletContextListener {

    /**
     * Default constructor. 
     */
    public InitializationServlet() {
    }


    static {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
        } catch (ClassNotFoundException cnfe) {
            cnfe.printStackTrace();
        }    
   }
	/**
     * @see ServletContextListener#contextInitialized(ServletContextEvent)
     */
    public void contextInitialized(ServletContextEvent arg0) {
        System.out.println("--> SI Creating USER table");

        try {
        	Context initContext = new InitialContext();
        	Context envContext  = (Context)initContext.lookup("java:/comp/env");
        	DataSource ds = (DataSource)envContext.lookup("jdbc/TestDB");

        	createUserTable(ds.getConnection());
        	//createUserTable(DriverManager.getConnection("jdbc:hsqldb:mem:.", "", ""));

        } catch (NamingException | SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } 
    }
    

	private void createUserTable(Connection con) throws SQLException {
        Statement stmt = con.createStatement();
        stmt.executeUpdate("create table USERS(id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY, name varchar(50))");
        stmt.executeUpdate("INSERT INTO users (name) values('Peter')");
        stmt.executeUpdate("INSERT INTO users (name) values('Paul')");
        stmt.executeUpdate("INSERT INTO users (name) values('Mary')");
        stmt.executeUpdate("INSERT INTO users (name) values('Ringo')");
        stmt.close();
    }

	/**
     * @see ServletContextListener#contextDestroyed(ServletContextEvent)
     */
    public void contextDestroyed(ServletContextEvent arg0) {
    }
	
}
