drop table if exists books;
drop table if exists authors;

create table books (
   id long generated by default as identity,
   author binary(255),
   isbn varchar(255),
   title varchar(255) not null,
   author_id bigint,
   primary key (id)
);

create table authors (
   id long generated by default as identity,
   name varchar(255) not null,
   primary key (id)
)